language: node_js

install:
  - npm install

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: "$GITHUB_TOKEN"
    local_dir: ./build/gh-pages
    email: deploy-openapi-spec@okta.com
    name: Okta OpenAPI Spec Deployment Bot
    on:
      branch: master
